version: '3.3'

services:
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    ports:
      - "127.0.0.1:10086:10086"
    volumes:
      - ./v2ray/config:/etc/v2ray
      - ./v2ray/log:/var/log/v2ray

  caddy:
    image: caddy
    restart: always
    depends_on:
      - v2ray
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
