version: '3.8'

services:
  v2ray:
    image: v2ray/official
    restart: always
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
    networks:
      - v2ray-caddy

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - v2ray-caddy

networks:
  v2ray-caddy:


volumes:
  caddy_data:
  caddy_config:
